stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/uber.csv
    outs:
      - data/processed/cleaned.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/processed/cleaned.csv
    outs:
      - data/processed/train_X.csv
      - data/processed/train_y.csv
      - data/processed/test_X.csv
      - data/processed/test_y.csv

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/train_X.csv
      - data/processed/train_y.csv
    outs:
      - model/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - model/model.pkl
      - data/processed/test_X.csv
      - data/processed/test_y.csv
